force-app/main/default/objects/VRT_Vehicle__c/VRT_Vehicle__c.object-meta.xml
<CustomObject>
    <description>Medio de transporte a alquilar.</description>
    <label>Vehículo</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Vehículo Number.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_DAT_ManufacturedYear__c.field-meta.xml
<CustomField>
    <fullName>VRT_DAT_ManufacturedYear__c</fullName>
    <description>Campo para introducir 
el año de fabricación del 
vehículo.</description>
    <label>Año de fabricación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_FLG_NeedsInspection__c.field-meta.xml
<CustomField>
    <fullName>VRT_FLG_NeedsInspection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Necesita_Revision_ITV</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_NUM_Passengers__c.field-meta.xml
<CustomField>
    <fullName>VRT_NUM_Passengers__c</fullName>
    <description>Campo numérico para 
especificar el número 
de pasajeros 
permitidos.</description>
    <label>Pasajeros</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_SEL_EnergyType__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_EnergyType__c</fullName>
    <description>Campo picklist para 
especificar el tipo de 
combustible o energía 
del vehículo.</description>
    <label>Combustible</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Eléctrico</fullName>
            </value>
            <value>
                <fullName>Híbrido</fullName>
            </value>
            <value>
                <fullName>Gasolina</fullName>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_Status__c</fullName>
    <description>Indica si el vehículo está 
listo para el alquiler o requiere mantenimiento.</description>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Listo</fullName>
            </value>
            <value>
                <fullName>En mantenimiento</fullName>
            </value>
            <value>
                <fullName>Fuera de Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_SEL_VehicleType__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_VehicleType__c</fullName>
    <description>Diferentes tipos de 
vehículos disponibles 
para alquiler.</description>
    <label>Tipo de vehículo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coche</fullName>
            </value>
            <value>
                <fullName>Moto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_TXT_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>VRT_TXT_LicensePlate__c</fullName>
    <description>Campo de texto para 
introducir la matrícula 
del vehículo.</description>
    <label>Matrícula</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VRT_CLS_CheckVehicleRevision_Test.cls
@IsTest
public class VRT_CLS_CheckVehicleRevision_Test {
    @IsTest
    static void testBatchRevision() {
        Integer currentYear = Date.today().year();

        VRT_Vehicle__c coche = new VRT_Vehicle__c(
            VRT_TXT_LicensePlate__c = '1234AAA',
            VRT_TXT_Brand__c         = 'Ford',
            VRT_SEL_VehicleType__c   = 'Coche',
            VRT_SEL_Status__c        = 'Listo',
            VRT_SEL_EnergyType__c    = 'Gasolina',
            VRT_NUM_Passengers__c    = 4,
            VRT_DAT_ManufacturedYear__c = Date.newInstance(currentYear-5,1,1),
            VRT_FLG_NeedsInspection__c  = false
        );
        VRT_Vehicle__c moto = new VRT_Vehicle__c(
            VRT_TXT_LicensePlate__c = '2345BBB',
            VRT_TXT_Brand__c         = 'Honda',
            VRT_SEL_VehicleType__c   = 'Moto',
            VRT_SEL_Status__c        = 'Listo',
            VRT_SEL_EnergyType__c    = 'Gasolina',
            VRT_NUM_Passengers__c    = 2,
            VRT_DAT_ManufacturedYear__c = Date.newInstance(currentYear-3,1,1),
            VRT_FLG_NeedsInspection__c  = false
        );
        VRT_Vehicle__c nuevo = new VRT_Vehicle__c(
            VRT_TXT_LicensePlate__c = '3456CCC',
            VRT_TXT_Brand__c         = 'Renault',
            VRT_SEL_VehicleType__c   = 'Coche',
            VRT_SEL_Status__c        = 'Listo',
            VRT_SEL_EnergyType__c    = 'Diesel',
            VRT_NUM_Passengers__c    = 5,
            VRT_DAT_ManufacturedYear__c = Date.newInstance(currentYear,1,1),
            VRT_FLG_NeedsInspection__c  = false
        );
        insert new List<VRT_Vehicle__c>{coche, moto, nuevo};

        // Ejecuta el batch
        Test.startTest();
        Database.executeBatch(new VRT_CLS_CheckVehicleRevision(), 200);
        Test.stopTest();

        coche = [SELECT VRT_FLG_NeedsInspection__c FROM VRT_Vehicle__c WHERE Id = :coche.Id];
        moto  = [SELECT VRT_FLG_NeedsInspection__c FROM VRT_Vehicle__c WHERE Id = :moto.Id];
        nuevo = [SELECT VRT_FLG_NeedsInspection__c FROM VRT_Vehicle__c WHERE Id = :nuevo.Id];
        System.assertEquals(true, coche.VRT_FLG_NeedsInspection__c, 'El coche viejo debe estar a true');
        System.assertEquals(true, moto.VRT_FLG_NeedsInspection__c, 'La moto también');
        System.assertEquals(false, nuevo.VRT_FLG_NeedsInspection__c, 'El coche nuevo debe estar a false');
    }
}