force-app/main/default/objects/VRT_Vehicle__c/VRT_Vehicle__c.object-meta.xml
<CustomObject>
    <description>Medio de transporte a alquilar.</description>
    <label>Vehículo</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Vehículo Number.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_TXT_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>VRT_TXT_LicensePlate__c</fullName>
    <description>Campo de texto para 
introducir la matrícula 
del vehículo.</description>
    <label>Matrícula</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_TXT_Model__c.field-meta.xml
<CustomField>
    <fullName>VRT_TXT_Model__c</fullName>
    <description>Campo para introducir 
el modelo del vehículo.</description>
    <label>Modelo</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VRT_CLS_VehicleSearchService.cls
// Clase que implementa la búsqueda de vehículos.
public with sharing class VRT_CLS_VehicleSearchService {
    //para conectar con LWC
    @AuraEnabled(cacheable=false)
    
    public static List<VRT_Vehicle__c> searchVehicles(String searchText) {

        if (!Schema.sObjectType.VRT_Vehicle__c.isAccessible()) {
        throw new SecurityException(
            'No tienes permisos para consultar vehículos.'
        );
        }
        
        if (String.isBlank(searchText)) {
            return new List<VRT_Vehicle__c>();
        }
        // Escapo los caracteres especiales y agrego comodines para la búsqueda
        String searchPattern = '*' + String.escapeSingleQuotes(searchText.trim()) + '*';
        // Realizo la búsqueda de vehículos utilizando SOSL
        List<List<SObject>> searchResults = [
            FIND :searchPattern
            IN ALL FIELDS
            RETURNING VRT_Vehicle__c(
                Id,
                Name,
                VRT_TXT_LicensePlate__c,
                VRT_TXT_Brand__c,
                VRT_TXT_Model__c
                LIMIT 20
            )
        ];
        // miro si el usuario tiene acceso a los campos de VRT_Vehicle__c y filtro los resultados en consecuencia
        SObjectAccessDecision accessDecision =
            Security.stripInaccessible(
                AccessType.READABLE,
                searchResults[0]
            );
        // Devuelvo los registros de vehículos filtrados
        return (List<VRT_Vehicle__c>) accessDecision.getRecords();
    }
}