force-app/main/default/objects/VRT_Invoice__c/VRT_Invoice__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Factura Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_Invoice__c/fields/VRT_CUR_TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>VRT_CUR_TotalAmount__c</fullName>
    <label>Importe Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VRT_Invoice__c/fields/VRT_DAT_IssueDate__c.field-meta.xml
<CustomField>
    <fullName>VRT_DAT_IssueDate__c</fullName>
    <description>fecha de emision de la factura</description>
    <label>Fecha de Emision</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VRT_Invoice__c/fields/VRT_LKP_Account__c.field-meta.xml
<CustomField>
    <fullName>VRT_LKP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VRT_Invoice__c/fields/VRT_LKP_Rental__c.field-meta.xml
<CustomField>
    <fullName>VRT_LKP_Rental__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Alquiler</label>
    <referenceTo>VRT_Rental__c</referenceTo>
    <relationshipLabel>Facturas</relationshipLabel>
    <relationshipName>Facturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VRT_Invoice__c/fields/VRT_SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_Status__c</fullName>
    <defaultValue>&quot;Emitida&quot;</defaultValue>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Borrador</fullName>
            </value>
            <value>
                <fullName>Emitida</fullName>
            </value>
            <value>
                <fullName>Pagada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_ProcessLog__c/VRT_ProcessLog__c.object-meta.xml
<CustomObject>
    <label>Process Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_ProcessLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_ProcessLog__c/fields/VRT_Execution_Date__c.field-meta.xml
<CustomField>
    <fullName>VRT_Execution_Date__c</fullName>
    <label>Execution Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/VRT_ProcessLog__c/fields/VRT_Invoice__c.field-meta.xml
<CustomField>
    <fullName>VRT_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice</referenceTo>
    <relationshipLabel>Process Logs</relationshipLabel>
    <relationshipName>Process_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VRT_ProcessLog__c/fields/VRT_LKP_Rental__c.field-meta.xml
<CustomField>
    <fullName>VRT_LKP_Rental__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Alquiler</label>
    <referenceTo>VRT_Rental__c</referenceTo>
    <relationshipLabel>Process Logs</relationshipLabel>
    <relationshipName>Process_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VRT_ProcessLog__c/fields/VRT_Message__c.field-meta.xml
<CustomField>
    <fullName>VRT_Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/VRT_Rental__c.object-meta.xml
<CustomObject>
    <description>Realiza el seguimiento de las operaciones de alquiler de los 
vehículos de la flota de la empresa.</description>
    <label>Alquiler</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Alquiler Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alquileres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_DIV_TotalCost__c.field-meta.xml
<CustomField>
    <fullName>VRT_DIV_TotalCost__c</fullName>
    <description>Este campo de moneda 
almacenará el coste total de la 
transacción de alquiler.</description>
    <label>Coste Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_LKP_Account__c.field-meta.xml
<CustomField>
    <fullName>VRT_LKP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Este campo de búsqueda 
establecerá una relación con el 
objeto &quot;Cuenta&quot;, permitiéndole 
asociar el alquiler con un cliente 
específico.</description>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Alquileres</relationshipLabel>
    <relationshipName>Alquileres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_Status__c</fullName>
    <description>Este campo de lista de selección 
indicará el estado del alquiler.</description>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>En curso</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VRT_CLS_InvoiceService.cls
public with sharing class VRT_CLS_InvoiceService {

    public static void createInvoices(List<VRT_Rental__c> rentals) {
        if (rentals == null || rentals.isEmpty()) {
            return;
        }

        Set<Id> rentalIds = new Set<Id>();

        for (VRT_Rental__c rental : rentals) {
            if (rental.Id != null) {
                rentalIds.add(rental.Id);
            }
        }

        if (rentalIds.isEmpty()) {
            return;
        }

        Set<Id> alreadyInvoicedRentalIds = new Set<Id>();

        for (VRT_Invoice__c invoice : [
            SELECT Id, VRT_LKP_Rental__c
            FROM VRT_Invoice__c
            WHERE VRT_LKP_Rental__c IN :rentalIds
        ]) {
            alreadyInvoicedRentalIds.add(invoice.VRT_LKP_Rental__c);
        }

        List<VRT_Invoice__c> invoicesToInsert = new List<VRT_Invoice__c>();
        List<VRT_ProcessLog__c> logsToInsert = new List<VRT_ProcessLog__c>();

        for (VRT_Rental__c rental : rentals) {
           if (alreadyInvoicedRentalIds.contains(rental.Id)) {
                logsToInsert.add(new VRT_ProcessLog__c(
                VRT_LKP_Rental__c = rental.Id,
                Status__c = 'Duplicate',
                VRT_Message__c = 'Invoice already exists. No duplicate invoice was created.',
                VRT_Execution_Date__c = System.now()
                ));

                continue;
            }

            invoicesToInsert.add(new VRT_Invoice__c(
                VRT_LKP_Rental__c = rental.Id,
                VRT_LKP_Account__c = rental.VRT_LKP_Account__c,
                VRT_CUR_TotalAmount__c = rental.VRT_DIV_TotalCost__c,
                VRT_DAT_IssueDate__c = Date.today(),
                VRT_SEL_Status__c = 'Emitida'
            ));

            logsToInsert.add(new VRT_ProcessLog__c(
                VRT_LKP_Rental__c = rental.Id,
                Status__c = 'Success',
                VRT_Message__c = 'Invoice created successfully.',
                VRT_Execution_Date__c = System.now()
            ));
        }

    try {

        if (!invoicesToInsert.isEmpty()) {
            insert invoicesToInsert;
        }

        if (!logsToInsert.isEmpty()) {
            insert logsToInsert;
        }
    
    } catch (Exception e) {

    List<VRT_ProcessLog__c> errorLogs = new List<VRT_ProcessLog__c>();

    for (VRT_Rental__c rental : rentals) {
            
            errorLogs.add(new VRT_ProcessLog__c(
            VRT_LKP_Rental__c = rental.Id,
            Status__c = 'Error',
            VRT_Message__c = e.getMessage(),
            VRT_Execution_Date__c = System.now()
            ));
        }

        if (!errorLogs.isEmpty()) {
            insert errorLogs;
        }

        throw e;
        }
    }
}