force-app/main/default/objects/VRT_Rental__c/VRT_Rental__c.object-meta.xml
<CustomObject>
    <description>Realiza el seguimiento de las operaciones de alquiler de los 
vehículos de la flota de la empresa.</description>
    <label>Alquiler</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Alquiler Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alquileres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_DAT_FinalDate__c.field-meta.xml
<CustomField>
    <fullName>VRT_DAT_FinalDate__c</fullName>
    <description>Este campo almacenará la fecha 
de finalización del periodo de 
alquiler.</description>
    <label>Fecha  Final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_DAT_InitialDate__c.field-meta.xml
<CustomField>
    <fullName>VRT_DAT_InitialDate__c</fullName>
    <description>Este campo almacenará la fecha 
de inicio del período de alquiler.</description>
    <label>Fecha Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_LKP_Account__c.field-meta.xml
<CustomField>
    <fullName>VRT_LKP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Este campo de búsqueda 
establecerá una relación con el 
objeto &quot;Cuenta&quot;, permitiéndole 
asociar el alquiler con un cliente 
específico.</description>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Alquileres</relationshipLabel>
    <relationshipName>Alquileres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_SEL_PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_PaymentStatus__c</fullName>
    <description>Este campo de lista de selección 
indicará el estado de pago del 
alquiler.</description>
    <label>Estado de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pagado</fullName>
            </value>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Atrasado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_Status__c</fullName>
    <description>Este campo de lista de selección 
indicará el estado del alquiler.</description>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>En curso</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VRT_CLS_RentalService_Test.cls
@IsTest
private class VRT_CLS_RentalService_Test {
    @testSetup
    static void setupData() {
    Account account = new Account(
        Name = 'Cliente Test'
    );
    insert account;

    Account account2 = new Account(
        Name = 'Cliente Test 2'
    );
    insert account2;

    List<VRT_Rental__c> rentals = new List<VRT_Rental__c>();

    rentals.add(new VRT_Rental__c(
        VRT_LKP_Account__c = account.Id,
        VRT_SEL_Status__c = 'Completado',
        VRT_SEL_PaymentStatus__c = 'Pagado',
        VRT_DAT_InitialDate__c = Date.today().addMonths(-2),
        VRT_DAT_FinalDate__c = Date.today().addMonths(-2).addDays(3)
    ));

    rentals.add(new VRT_Rental__c(
        VRT_LKP_Account__c = account.Id,
        VRT_SEL_Status__c = 'Completado',
        VRT_SEL_PaymentStatus__c = 'Pagado',
        VRT_DAT_InitialDate__c = Date.today().addMonths(-4),
        VRT_DAT_FinalDate__c = Date.today().addMonths(-4).addDays(3)
    ));

    rentals.add(new VRT_Rental__c(
        VRT_LKP_Account__c = account.Id,
        VRT_SEL_Status__c = 'Completado',
        VRT_SEL_PaymentStatus__c = 'Pagado',
        VRT_DAT_InitialDate__c = Date.today().addMonths(-6),
        VRT_DAT_FinalDate__c = Date.today().addMonths(-6).addDays(3)
    ));

    rentals.add(new VRT_Rental__c(
        VRT_LKP_Account__c = account.Id,
        VRT_SEL_Status__c = 'Cancelado',
        VRT_SEL_PaymentStatus__c = 'Pagado',
        VRT_DAT_InitialDate__c = Date.today().addMonths(-1),
        VRT_DAT_FinalDate__c = Date.today().addMonths(-1).addDays(2)
    ));

    rentals.add(new VRT_Rental__c(
        VRT_LKP_Account__c = account.Id,
        VRT_SEL_Status__c = 'Completado',
        VRT_SEL_PaymentStatus__c = 'Pagado',
        VRT_DAT_InitialDate__c = Date.today().addMonths(-18),
        VRT_DAT_FinalDate__c = Date.today().addMonths(-18).addDays(2)
    ));

    rentals.add(new VRT_Rental__c(
        VRT_LKP_Account__c = account2.Id,
        VRT_SEL_Status__c = 'Completado',
        VRT_SEL_PaymentStatus__c = 'Pagado',
        VRT_DAT_InitialDate__c = Date.today().addMonths(-3),
        VRT_DAT_FinalDate__c = Date.today().addMonths(-3).addDays(3)
    ));

    insert rentals;
    }

    @IsTest
static void testCountCompletedRentalsLast12Months() {

    Account account = [
        SELECT Id
        FROM Account
        WHERE Name = 'Cliente Test'
        LIMIT 1
    ];

    Integer completedRentals =
        VRT_CLS_RentalService.countCompletedRentalsLast12Months(
            account.Id
        );

    System.assertEquals(
        3,
        completedRentals,
        'Debe contar únicamente los alquileres completados de los últimos 12 meses.'
    );
}


}