force-app/main/default/objects/VRT_Rental__c/VRT_Rental__c.object-meta.xml
<CustomObject>
    <description>Realiza el seguimiento de las operaciones de alquiler de los 
vehículos de la flota de la empresa.</description>
    <label>Alquiler</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Alquiler Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alquileres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_DAT_FinalDate__c.field-meta.xml
<CustomField>
    <fullName>VRT_DAT_FinalDate__c</fullName>
    <description>Este campo almacenará la fecha 
de finalización del periodo de 
alquiler.</description>
    <label>Fecha  Final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_DAT_InitialDate__c.field-meta.xml
<CustomField>
    <fullName>VRT_DAT_InitialDate__c</fullName>
    <description>Este campo almacenará la fecha 
de inicio del período de alquiler.</description>
    <label>Fecha Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_LKP_Account__c.field-meta.xml
<CustomField>
    <fullName>VRT_LKP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Este campo de búsqueda 
establecerá una relación con el 
objeto &quot;Cuenta&quot;, permitiéndole 
asociar el alquiler con un cliente 
específico.</description>
    <label>Cuenta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Alquileres</relationshipLabel>
    <relationshipName>Alquileres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_LKP_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>VRT_LKP_Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Este campo de búsqueda 
establecerá una relación con el 
objeto &quot;Vehículo&quot;, permitiéndole 
asociar el alquiler con un 
vehículo específico.</description>
    <label>Vehículo</label>
    <referenceTo>VRT_Vehicle__c</referenceTo>
    <relationshipLabel>Alquileres</relationshipLabel>
    <relationshipName>Alquileres</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_SEL_PaymentStatus__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_PaymentStatus__c</fullName>
    <description>Este campo de lista de selección 
indicará el estado de pago del 
alquiler.</description>
    <label>Estado de Pago</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pagado</fullName>
            </value>
            <value>
                <fullName>Pendiente</fullName>
            </value>
            <value>
                <fullName>Atrasado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_Status__c</fullName>
    <description>Este campo de lista de selección 
indicará el estado del alquiler.</description>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>En curso</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/VRT_Vehicle__c.object-meta.xml
<CustomObject>
    <description>Medio de transporte a alquilar.</description>
    <label>Vehículo</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Vehículo Number.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehículos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_DAT_ManufacturedYear__c.field-meta.xml
<CustomField>
    <fullName>VRT_DAT_ManufacturedYear__c</fullName>
    <description>Campo para introducir 
el año de fabricación del 
vehículo.</description>
    <label>Año de fabricación</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_FLG_Available__c.field-meta.xml
<CustomField>
    <fullName>VRT_FLG_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo checkbox para 
indicar si el vehículo 
está disponible para 
alquiler en un momento 
determinado.</description>
    <label>Disponible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_FLG_NeedsInspection__c.field-meta.xml
<CustomField>
    <fullName>VRT_FLG_NeedsInspection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Necesita_Revision_ITV</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_NUM_Passengers__c.field-meta.xml
<CustomField>
    <fullName>VRT_NUM_Passengers__c</fullName>
    <description>Campo numérico para 
especificar el número 
de pasajeros 
permitidos.</description>
    <label>Pasajeros</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_SEL_EnergyType__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_EnergyType__c</fullName>
    <description>Campo picklist para 
especificar el tipo de 
combustible o energía 
del vehículo.</description>
    <label>Combustible</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Eléctrico</fullName>
            </value>
            <value>
                <fullName>Híbrido</fullName>
            </value>
            <value>
                <fullName>Gasolina</fullName>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>Otro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_Status__c</fullName>
    <description>Indica si el vehículo está 
listo para el alquiler o requiere mantenimiento.</description>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Listo</fullName>
            </value>
            <value>
                <fullName>En mantenimiento</fullName>
            </value>
            <value>
                <fullName>Fuera de Servicio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_SEL_VehicleType__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_VehicleType__c</fullName>
    <description>Diferentes tipos de 
vehículos disponibles 
para alquiler.</description>
    <label>Tipo de vehículo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coche</fullName>
            </value>
            <value>
                <fullName>Moto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VRT_Vehicle__c/fields/VRT_TXT_LicensePlate__c.field-meta.xml
<CustomField>
    <fullName>VRT_TXT_LicensePlate__c</fullName>
    <description>Campo de texto para 
introducir la matrícula 
del vehículo.</description>
    <label>Matrícula</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VRT_CLS_AvailabilityService_Test.cls
@IsTest
private class VRT_CLS_AvailabilityService_Test {

    @IsTest
    static void testReturnsUnavailableVehicleWhenDatesOverlap() {

        // ARRANGE
        Account account = new Account(
            Name = 'Test Availability Account'
        );
        insert account;

        VRT_Vehicle__c vehicle = new VRT_Vehicle__c(
        VRT_TXT_LicensePlate__c = '9999ZZZ',
        VRT_TXT_Brand__c = 'Ford',
        VRT_SEL_VehicleType__c = 'Coche',
        VRT_SEL_Status__c = 'Listo',
        VRT_SEL_EnergyType__c = 'Gasolina',
        VRT_NUM_Passengers__c = 4,
        VRT_DAT_ManufacturedYear__c = Date.newInstance(2021, 1, 1),
        VRT_FLG_NeedsInspection__c = false,
        VRT_FLG_Available__c = true
    );

        insert vehicle;

        VRT_Rental__c rental = new VRT_Rental__c(
            VRT_LKP_Account__c = account.Id,
            VRT_LKP_Vehicle__c = vehicle.Id,
            VRT_SEL_Status__c = 'Reservado',
            VRT_SEL_PaymentStatus__c = 'Pagado',
            VRT_DAT_InitialDate__c = Date.today().addDays(5),
            VRT_DAT_FinalDate__c = Date.today().addDays(10)
        );
        insert rental;

        // ACT
        Set<Id> unavailableVehicleIds =
            VRT_CLS_AvailabilityService.getUnavailableVehicleIds(
                Date.today().addDays(7),
                Date.today().addDays(12)
            );

        // ASSERT
        System.assert(
            unavailableVehicleIds.contains(vehicle.Id),
            'El vehículo debería estar ocupado porque las fechas se solapan.'
        );
    }


    @IsTest
    static void testDoesNotReturnVehicleWithoutOverlap() {

        // ARRANGE
        Account account = new Account(
            Name = 'Test Availability Account'
        );
        insert account;

        VRT_Vehicle__c vehicle = new VRT_Vehicle__c(
                VRT_TXT_LicensePlate__c = '9999ZZZ',
                VRT_TXT_Brand__c = 'Ford',
                VRT_SEL_VehicleType__c = 'Coche',
                VRT_SEL_Status__c = 'Listo',
                VRT_SEL_EnergyType__c = 'Gasolina',
                VRT_NUM_Passengers__c = 4,
                VRT_DAT_ManufacturedYear__c = Date.newInstance(2021, 1, 1),
                VRT_FLG_NeedsInspection__c = false,
                VRT_FLG_Available__c = true
            );

        insert vehicle;

        VRT_Rental__c rental = new VRT_Rental__c(
            VRT_LKP_Account__c = account.Id,
            VRT_LKP_Vehicle__c = vehicle.Id,
            VRT_SEL_Status__c = 'Reservado',
            VRT_SEL_PaymentStatus__c = 'Pagado',
            VRT_DAT_InitialDate__c = Date.today().addDays(5),
            VRT_DAT_FinalDate__c = Date.today().addDays(10)
        );
        insert rental;

        // ACT
        Set<Id> unavailableVehicleIds =
            VRT_CLS_AvailabilityService.getUnavailableVehicleIds(
                Date.today().addDays(15),
                Date.today().addDays(20)
            );

        // ASSERT
        System.assert(
            !unavailableVehicleIds.contains(vehicle.Id),
            'El vehículo debería estar disponible porque no existe solapamiento.'
        );
    }


    @IsTest
    static void testAllowsSameDayEndStart() {

        // ARRANGE
        Account account = new Account(
            Name = 'Test Availability Account'
        );
        insert account;

        VRT_Vehicle__c vehicle = new VRT_Vehicle__c(
        VRT_TXT_LicensePlate__c = '9999ZZZ',
        VRT_TXT_Brand__c = 'Ford',
        VRT_SEL_VehicleType__c = 'Coche',
        VRT_SEL_Status__c = 'Listo',
        VRT_SEL_EnergyType__c = 'Gasolina',
        VRT_NUM_Passengers__c = 4,
        VRT_DAT_ManufacturedYear__c = Date.newInstance(2021, 1, 1),
        VRT_FLG_NeedsInspection__c = false,
        VRT_FLG_Available__c = true
    );

        insert vehicle;

        VRT_Rental__c rental = new VRT_Rental__c(
            VRT_LKP_Account__c = account.Id,
            VRT_LKP_Vehicle__c = vehicle.Id,
            VRT_SEL_Status__c = 'Reservado',
            VRT_SEL_PaymentStatus__c = 'Pagado',
            VRT_DAT_InitialDate__c = Date.today().addDays(5),
            VRT_DAT_FinalDate__c = Date.today().addDays(10)
        );
        insert rental;

        // ACT
        Set<Id> unavailableVehicleIds =
            VRT_CLS_AvailabilityService.getUnavailableVehicleIds(
                Date.today().addDays(10),
                Date.today().addDays(15)
            );

        // ASSERT
        System.assert(
            !unavailableVehicleIds.contains(vehicle.Id),
            'El vehículo debería estar disponible si un alquiler empieza el mismo día que termina el anterior.'
        );
    }
}