force-app/main/default/objects/VRT_Rental__c/VRT_Rental__c.object-meta.xml
<CustomObject>
    <description>Realiza el seguimiento de las operaciones de alquiler de los 
vehículos de la flota de la empresa.</description>
    <label>Alquiler</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Alquiler Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alquileres</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VRT_Rental__c/fields/VRT_SEL_Status__c.field-meta.xml
<CustomField>
    <fullName>VRT_SEL_Status__c</fullName>
    <description>Este campo de lista de selección 
indicará el estado del alquiler.</description>
    <label>Estado</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>En curso</fullName>
            </value>
            <value>
                <fullName>Completado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VRT_TRG_RentalHandler.cls
public with sharing class VRT_TRG_RentalHandler {
    
    public static void onAfterInsert(List<VRT_Rental__c> newRentals) {
        VRT_TRG_RentalHandlerHelper.updateConditionVehicle(newRentals);
    }        
    public static void onAfterUpdate(
    Map<Id, VRT_Rental__c> oldMap,
    Map<Id, VRT_Rental__c> newMap
    ) {
    VRT_TRG_RentalHandlerHelper.updateVehicleRentalCompleted(oldMap, newMap);

    List<VRT_Rental__c> rentalsToInvoice = new List<VRT_Rental__c>();

    for (VRT_Rental__c rental : newMap.values()) {
        VRT_Rental__c oldRental = oldMap.get(rental.Id);

        if (
            rental.VRT_SEL_Status__c == 'Completado' &&
            oldRental.VRT_SEL_Status__c != 'Completado'
        ) {
            rentalsToInvoice.add(rental);
        }
    }

    if (!rentalsToInvoice.isEmpty()) {
        System.enqueueJob(new VRT_CLS_InvoiceQueueable(rentalsToInvoice));
    }
    }
    public static void onBeforeInsert(List<VRT_Rental__c> newRentals) {
        VRT_CLS_RentalService.validateVehicleAvailability(
            newRentals,
            null
        );
        
        VRT_CLS_RentalService.calculateRentalPrices(newRentals);
    }

    public static void onBeforeUpdate(
        Map<Id,VRT_Rental__c> oldMap,
        Map<Id,VRT_Rental__c> newMap) 
    {
        VRT_TRG_RentalHandlerHelper.setActualReturnDateWhenCompleted(
        oldMap,
        newMap
        );
        VRT_CLS_RentalService.validateVehicleAvailability(
        new List<VRT_Rental__c>(newMap.values()),
        oldMap
        );
        
        VRT_CLS_RentalService.calculateRentalPrices(
        new List<VRT_Rental__c>(newMap.values())
        );
    }
}